menu:
  Blog: archives
  #Projects: projects
  #Notes: notes
  About: about

widgets: []
#- search
#- category
#- tag

excerpt_link: Read More

twitter:
  username: jaekwon
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: false
  twitter: false
  google: false
  pinterest: false

fancybox: true

google_analytics:
rss:

comment_provider: disqus
# Facebook comment
facebook:
  appid: 123456789012345
  comment_count: 5
  comment_width: 840
  comment_colorscheme: sidebar
